default_language_version:
  python: python3.11.3
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.10.0]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        name: Run codespell to check for common misspellings in files
        language: python
        types: [ text ]
        args: [ "--write-changes", "--ignore-words-list", "asend" ]
        exclude: "poetry.lock"


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
        # exclude: "tests/((commands|data)/|test_).+"
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: debug-statements
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [ '--unsafe' ] # for mkdocs.yml
      - id: detect-private-key

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - push

  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        pass_filenames: false
        entry: make format
        types: [ python ]

      - id: linter
        name: linter
        language: system
        pass_filenames: false
        stages: [ push ]
        entry: make lint
        types: [ python ]

      - id: test
        name: test
        language: system
        pass_filenames: false
        stages: [ push ]
        entry: make test
        types: [ python ]
