[tool.poetry]
name = "decision-layer"
version = "0.0.1"
description = "Super fast decision layer for AI"
authors = ["James Briggs <james@aurelio.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.2"


[tool.poetry.group.extras.dependencies]
openai = "^0.28.1"
transformers = "^4.34.1"
cohere = "^4.32"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
